version: '3'

services:

  notebook:
    image: tensorflow/tensorflow:1.15.2-py3-jupyter
    container_name: know_your_mind
    volumes:
      - ./app/src:/tf/know_your_mind
      - ./data:/tf/data
      - ./notebooks:/tf/notebooks
    ports:
      - 8888:8888
      - 5678:5678
    user: 1000:1000
    command:
      - jupyter
      - notebook
      - --NotebookApp.token=''
      - --ip=0.0.0.0
      - --no-browser
